services:
  - type: web
    name: secret-santa-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: secret_santa_db
      - key: CORS_ORIGINS
        value: '*'
      - key: PYTHON_VERSION
        value: '3.11'
